# Generated by Django 3.0.4 on 2020-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200909_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestemp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rahul',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
