# Generated by Django 3.0.4 on 2020-09-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200911_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestemp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
