# Generated by Django 3.0.4 on 2020-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_singup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gali', models.CharField(max_length=200)),
                ('shrignash', models.CharField(max_length=100)),
                ('delhibazzer', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='delhibazzer',
        ),
        migrations.RemoveField(
            model_name='table',
            name='gali',
        ),
        migrations.RemoveField(
            model_name='table',
            name='shrignash',
        ),
    ]
