# Generated by Django 3.0.4 on 2020-09-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200913_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
