# Generated by Django 3.0.4 on 2021-03-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dhanlaxmi',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='disawer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='fridabad',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='gaziyabad',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='gali',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rahul',
            name='num',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='fridabad',
            field=models.CharField(max_length=100),
        ),
    ]
